name: Autograding

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile and Run Hidden Tests
        run: |
          g++ .github/classroom/test_array_ops.cpp starter_code/array_ops.cpp -o test
          ./test
